import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    padding: 24,
    backgroundColor: "#fff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    marginHorizontal: 30,
    marginVertical: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    marginTop: 12,
    color: "#55bb32",
  },
  text: {
    fontSize: 16,
    marginBottom: 8,
    color: "#333",
  },
  textReport: {
    fontSize: 16,
    marginBottom: 10,
    color: "#333",
    paddingHorizontal: 30,
  },
  bold: {
    fontWeight: "bold",
    color: "#55bb32",
  },
  card: {
    padding: 24,
    backgroundColor: "#fff",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    marginHorizontal: 30,
    marginVertical: 5,
    fontSize: 16,
  },
  averageContainer: {
    padding: 12,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#ccc",
    alignItems: "center",
  },
  averageText: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#55bb32",
  },
  pickerWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    marginBottom: 10,
  },
  picker: {
    height: 60,
    color: "#333", // opcional: cambiar color de texto
  },
  toggleButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    marginTop: 10,
    marginLeft: 30,
  },
  toggleText: {
    color: "#55bb32",
    fontWeight: "bold",
    marginRight: 6,
  },
  filtersContainer: {
    marginBottom: 12,
  },
  infoText: {
    marginBottom: 16,
    fontSize: 16,
    color: "#333",
  },
  label: {
    fontWeight: "bold",
    marginTop: 12,
    marginBottom: 6,
    color: "#55bb32",
  },
  input: {
    height: 60,
    borderColor: "#ccc",
    borderWidth: 1,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 20,
  },
  description: {
    marginBottom: 30,
    fontSize: 16,
    textAlign: "center",
  },
  buttonContainer: {
    marginBottom: 15,
  },
  motivation: {
    marginTop: 40,
    alignItems: "center",
  },
  motivationLine: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#55bb32",
  },
  registerText: {
    color: "#55bb32",
    textAlign: "center",
    marginTop: 24,
    textDecorationLine: "none",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
  },
  button: {
    flexDirection: "row",
    backgroundColor: "#55bb32",
    paddingVertical: 14,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  link: {
    color: "#55bb32",
    textDecorationLine: "underline",
    fontWeight: "bold",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "80%",
    backgroundColor: "#fff",
    padding: 24,
    borderRadius: 12,
    alignItems: "center",
    position: "relative",
  },
  closeButton: { position: "absolute", top: 12, right: 12 },
  // title: {
  //   fontSize: 20,
  //   fontWeight: "bold",
  //   color: "#55bb32",
  //   marginBottom: 12,
  //   textAlign: "center",
  // },
  message: {
    fontSize: 16,
    color: "#333",
    marginBottom: 20,
    textAlign: "center",
  },
  modalButton: {
    backgroundColor: "#55bb32",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  modalButtonText: { color: "white", fontWeight: "bold" },
});
